server:
  port: 7778
  tomcat:
    uri-encoding: utf-8

# 配置数据源
spring:
  http:
    encoding:
      charset: utf-8
  application:
    name: test2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_test2?serverTimezone=Asia/Shanghai
    username: root
    password: root

# 指定映射文件的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 微服务
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    port: 9999
  client:
      serviceUrl:
        defaultZone: http://admin:151417eureka@${eureka.instance.ip-address}:${eureka.instance.port}/eureka/