server:
  port: 7777
  tomcat:
    uri-encoding: utf-8
    # 设定tomcat的basedir目录，如果没有指定则使用临时目录
    basedir: /home/app/tomcat_upload_temp

# 配置数据源
spring:
  http:
    encoding:
      charset: utf-8
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.236.223:3306/java_test?serverTimezone=Asia/Shanghai
    username: root
    password: 151417mysql
# redis
  redis:
    database: 0
    host: 175.178.236.223
    port: 6379
    timeout: 3000
    password: 151417redis
  servlet:
    # 上传限定参数
    multipart:
      # 是否启用分段上传支持
      enabled: true
      # 最大请求大小
      max-request-size: 20MB
      # 最大文件的大小
      max-file-size: 20MB
      # 上传文件的中间位置
      location: /home/app/tomcat_upload_temp

# 指定映射文件的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 微服务
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 175.178.236.223
    port: 9999
  client:
    serviceUrl:
      defaultZone: http://admin:151417eureka@${eureka.instance.ip-address}:${eureka.instance.port}/eureka/

student:
  a: "学生a"